apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: "idi2019.azurecr.io/dwo1327-gb-b"
        args: [ConnectionStrings:dbconnection=Server=mariadb;Database={{ .Values.database.name }};User Id={{ .Values.database.name }};Password=$(MYSQL_USER_PASSWORD);]
        name: backend
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
              secretKeyRef:
                  name: dbpassword
                  key: rootpassword
        - name: MYSQL_USER_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: dbpassword
                  key: password
        ports:
        - containerPort: 8080
          name: backend