apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
              secretKeyRef:
                  name: dbpassword
                  key: rootpassword
        - name: MYSQL_DATABASE
          value: {{ .Values.database.name }}
        - name: MYSQL_USER
          value: {{ .Values.database.name }}
        - name: MYSQL_PASSWORD
          valueFrom: 
              secretKeyRef:
                  name: dbpassword
                  key: password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mariadb
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: foo
        secret:
          secretName: mysecret
