apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
          # Use secret in real usage
        - name: usernamesecret
            valueFrom:
              secretKeyRef:
                name: secret-maria
                key: username
        - name: passwordsecret
            valueFrom:
              secretKeyRef:
                name: secret-maria
                key: password
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: $usernamesecret
        - name: MYSQL_USER
          value: $usernamesecret
        - name: MYSQL_PASSWORD
          value: $passwordsecret
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mariadb
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: foo
        secret:
          secretName: mysecret